"""
scripts/08_validate_golden_set.py
---------------------------------
Validates the Golden Set for:
- Correct number of examples (150-250)
- No duplicates
- Valid intents from the taxonomy
- Distribution of labels
"""

import sys
from pathlib import Path
import pandas as pd
import yaml

CSV_PATH = Path("data/gold/amazonhelp_golden_set.csv")
YAML_PATH = Path("configs/intent_taxonomy.yaml")
REPORT_PATH = Path("reports/golden_set_validation.md")
REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)

def section(title):
    print(f"\n{'='*60}\n  {title}\n{'='*60}")

def main():
    if not CSV_PATH.exists():
        print(f"[ERROR] Golden Set not found: {CSV_PATH}")
        sys.exit(1)
    if not YAML_PATH.exists():
        print(f"[ERROR] Taxonomy not found: {YAML_PATH}")
        sys.exit(1)

    df = pd.read_csv(CSV_PATH)
    with open(YAML_PATH, "r") as f:
        tax = yaml.safe_load(f)
    valid_intents = [i["name"] for i in tax.get("intents", [])]
    valid_intents.append("UNLABELED") # Allowed during work-in-progress

    section("VALIDATING GOLDEN SET")
    errors = []
    
    # 1. Count
    count = len(df)
    if not (150 <= count <= 250):
        errors.append(f"Row count {count} is outside the 150-250 range.")
    
    # 2. Duplicates
    dup_ids = df["example_id"].duplicated().sum()
    if dup_ids > 0:
        errors.append(f"Found {dup_ids} duplicate example_ids.")
        
    # 3. Missing Text
    missing_text = df["customer_text"].isna().sum()
    if missing_text > 0:
        errors.append(f"Found {missing_text} missing customer texts.")
        
    # 4. Valid Intents
    invalid_intents = df[~df["intent"].isin(valid_intents)]["intent"].unique()
    if len(invalid_intents) > 0:
        errors.append(f"Found invalid intents: {invalid_intents}")

    # 5. Labeling Progress
    unlabeled = (df["intent"] == "UNLABELED").sum()
    labeled = count - unlabeled

    # Distributions
    intent_dist = df[df["intent"] != "UNLABELED"]["intent"].value_counts().to_dict()
    diff_dist = df[df["difficulty"].notna()]["difficulty"].value_counts().to_dict()

    if errors:
        print("[!] Validation failed with errors:")
        for e in errors:
            print(f"  - {e}")
    else:
        print("[OK] All data structure checks passed.")

    print(f"\nProgress: {labeled}/{count} labeled.")

    # Generate Report
    md = [
        "# Golden Set Validation Report",
        "Generated by: `scripts/08_validate_golden_set.py`",
        "",
        "## Overall Status",
        f"- **Total Examples**: {count}",
        f"- **Labeled**: {labeled}",
        f"- **Unlabeled**: {unlabeled}",
        ""
    ]

    if errors:
        md.append("## ❌ Validation Errors")
        for e in errors:
            md.append(f"- {e}")
        md.append("")
    else:
        md.append("## ✅ Data Integrity Checks Passed")
        md.append("- Row count is within 150-250 limit.")
        md.append("- No duplicate example IDs.")
        md.append("- No missing customer text.")
        md.append("- All assigned intents belong to the defined taxonomy.")
        md.append("")

    md.append("## Label Distribution")
    if intent_dist:
        for i, c in intent_dist.items():
            md.append(f"- `{i}`: {c}")
    else:
        md.append("- *No labels assigned yet.*")
    md.append("")

    md.append("## Difficulty Distribution")
    if diff_dist:
        for d, c in diff_dist.items():
            md.append(f"- `{d}`: {c}")
    else:
        md.append("- *No difficulty assigned yet.*")

    REPORT_PATH.write_text("\n".join(md), encoding="utf-8")
    print(f"\n[OK] Validation report saved to {REPORT_PATH}")

if __name__ == "__main__":
    main()
